name: renew all

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:

  renew:
    runs-on: ubuntu-latest
    env:
      DEPLOY_DIR: ${{ matrix.deploydir }}
      DOT_CONFIG: ${{ matrix.dotconfig }}
    strategy:
      fail-fast: false
      matrix:
        deploydir:
          - preset-lede
          - preset-openwrt
          - preset-immortalwrt
          - preset-lienol-openwrt
          - preset-x-wrt
        dotconfig:
          - 1.config
          - 2.config
        include:
          - deploydir: preset-openwrt
            dotconfig: multi-common.config
          - deploydir: preset-openwrt
            dotconfig: multi-mini.config
    steps:

    - uses: actions/checkout@v4

    - name: Carry out
      env:
        RENEW_PY: extra-files/renew.py
      run: |
        chmod +x $RENEW_PY
        $RENEW_PY

    - uses: actions/upload-artifact@v4
      with:
        name: ${{ env.DEPLOY_DIR }}
        path: ${{ env.DEPLOY_DIR }}

  commit:
    if: always()
    needs: renew
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v3
    
    - uses: actions/download-artifact@v3
      
    - uses: geekyeggo/delete-artifact@v2
      with:
          name: '*'

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: renew .config files 
        commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
